name: Build and test

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  WORKSPACE_PATH: ros_ws
  CLONE_PATH: ros_ws/src/${{ github.events.repo.name }}

# only run one build doc workflow at a time, cancel any running ones
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - humble
          - iron
          - rolling
        include:
          # Humble Hawksbill (May 2022 - May 2027)
          - ros_distribution: humble
            docker_image: rostooling/setup-ros-docker:ubuntu-jammy-ros-humble-ros-base-latest
          # Iron Irwini (May 2023 - November 2024)
          - ros_distribution: iron
            docker_image: rostooling/setup-ros-docker:ubuntu-jammy-ros-iron-ros-base-latest
          # Rolling Ridley (June 2020 - Present)
          - ros_distribution: rolling
            docker_image: rostooling/setup-ros-docker:ubuntu-jammy-ros-rolling-ros-base-latest
    container:
      image: ${{ matrix.docker_image }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup workspace
        run: mkdir -p ${{ env.CLONE_PATH }}
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: ${{ env.CLONE_PATH }}
      - name: Build and test
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: dynmsg dynmsg_demo dynmsg_msgs test_dynmsg
          target-ros2-distro: ${{ matrix.ros_distribution }}
      - name: Upload logs as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build_and_test_logs_${{ matrix.ros_distribution }}
          path: ${{ env.WORKSPACE_PATH }}/log
